
<div data-bind="scope:'suraj-component'">
    <h2 data-bind="text:title"></h2>
    <ul>
        <!--ko foreach: {data:getItems(), as: 'page' } -->
        <li><a data-bind="text: page "></a></li>
        <!--/ko-->
    </ul>
</div>

<script type="text/x-magento-init">
    {
        "*":{
            "Magento_Ui/js/core/app":{
                "components":{
                    "suraj-component":{
                        "component":"Magento360_CustomeName/js/custom-name",
                        "title":"Buyed Names With Items!"
                    }
                }
            }
        }
    }
</script>
